name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-16.04    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Build
      env:
        GOPATH: /home/runner/work/
      run: make deps bindata build
